version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: bilerman_app
    ports:
      - "8888:8888"
    depends_on:
      - db

  db:
    image: 'postgres:14'
    volumes:
      - /root/bilerman_data/postgres/data:/var/lib/postgresql/data/
    container_name: bilerman_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
