version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    volumes:
      - /root/bilerman_data/app/images:/app/images:rw
    container_name: bilerman_app
    ports:
      - "8443:8888"
    depends_on:
      - db
    env_file: ~/bilerman_data/app/.env
    environment:
      - SPRING_MAIL_USERNAME="${SPRING_MAIL_USERNAME}"
      - SPRING_MAIL_PASSWORD="${SPRING_MAIL_PASSWORD}"

  db:
    image: 'postgres:14'
    volumes:
      - /root/bilerman_data/postgres/data:/var/lib/postgresql/data/
    container_name: bilerman_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
